### ISSUE TITLE
A screenshot web component

### ISSUE THREAD

**Issue by zachleat** [zachleat/idea-book#23]
Customizable viewport size, toggle between JS enabled and not.

https://pptr.dev/#?product=Puppeteer&version=v5.5.0&show=api-pagescreenshotoptions

Stretch goal: Allow scrolling?

Would be great for https://www.11ty.dev/

**Comment by nhoizey** [comment]
Would it make a screenshot of the page where the component is used?

If so, that means all screenshots made with the component have the screenshot button visible? 🤔

**Comment by zachleat** [comment]
Ah, no sorry, you’d point it at a URL and it would display the screenshot of that URL.

I’m thinking a reusable thing for this (with a few more features) on the 11ty.dev home page and author pages:

![image](https://user-images.githubusercontent.com/39355/113887622-44779980-9787-11eb-8edd-eb7da885fbf8.png)

**Comment by nhoizey** [comment]
Oooh, ok, now I understand.

I currently use thum.io for this (but it's limited), and resize with Cloudinary. A simple local solution would be great indeed! 👍

**Comment by zachleat** [comment]
(For future me) I did build a demo of this but it’s kinda half baked and not public yet. Dunno if I’ll circle back to it but a private repo is here: https://github.com/11ty/component-screenshot

![screenshot scroller](https://user-images.githubusercontent.com/39355/140327893-4bb9cbe0-4e71-4197-88a2-75c2be9b622b.gif)

**Comment by nhoizey** [comment]
I don't really understand what happens here… 😅

It this whole animation an automated screencast with a mouse pointer "activating" an iframe and scrolling inside?

**Comment by zachleat** [comment]
It starts out with a standard screenshot, and then you can click to activate and load a full page screenshot in the same pane (which is scrollable). Not sure if it’s practical or worth it 😅 which is why I’ll probably just leave it private.

Gonna close this one

**Comment by nhoizey** [comment]
Ok! 😅
