### ISSUE TITLE
Responsive Images Efficiency Analyzer

### ISSUE THREAD

**Issue by zachleat** [zachleat/idea-book#3]
Tests the efficiency of the bitmap images you have on your page at different screen resolutions.

Resize the page and then measure an image’s rendered dimensions versus the image’s natural dimensions, report retina rating (2x, 3x, .5x) and give some kind of efficiency score.

Maybe also report amount of wire-weight image savings between breakpoints.

Not sure if this would be a build tool or a bookmarklet (or both).

**Comment by nhoizey** [comment]
Looks a little like @yoavweiss ' Sizer Soze: https://blog.yoav.ws/who_is_sizer_soze/

**Comment by zachleat** [comment]
Ah yes! I’d forgotten about this (I’m even listed on the contributors list there 😱), thanks @nhoizey!

Looks like it might be down though, I got this error when I tried it: https://github.com/ResponsiveImagesCG/Sizer-Soze-frontend/issues/51

**Comment by nhoizey** [comment]
You're welcome! ;-)

I hope it will be fixed.

**Comment by zachleat** [comment]
Closing, this is exactly what I wanted: https://chrome.google.com/webstore/detail/ncc-image-checker/fphiheficgnpphmjdliclanppccfgifl

**Comment by zachleat** [comment]
Hmm, I think I’m going to reopen this. It’s very close! I want to see a report across a bunch of different viewport sizes.

**Comment by zachleat** [comment]
https://github.com/nccgroup/image-checker/issues

**Comment by nhoizey** [comment]
Also, it doesn't seem to work very well: https://github.com/nccgroup/image-checker/issues/29

**Comment by zachleat** [comment]
You mean, not yet! Let’s contribute to this thing 🙂

**Comment by nhoizey** [comment]
Indeed! ;-)

**Comment by simonhearne** [comment]
Perhaps combining the image checker with something like [Breakpoint Tester](http://breakpointtester.com/) would provide a good solution?

**Comment by zachleat** [comment]
@simonhearne that’s a fantastic idea!

**Comment by zachleat** [comment]
Just for posterity I’m going to include https://webspeedtest.cloudinary.com/ as well, although it uses a fixed viewport size and DPI.

**Comment by nhoizey** [comment]
https://twitter.com/zachleat/status/974838687338041344

**Comment by zachleat** [comment]
Launched! https://github.com/filamentgroup/imaging-heap
